### ISSUE TITLE
v5: How to change default Controllers path?

### ISSUE THREAD

**Issue by LuanMaik** [adonisjs/application#18]
AdonisJs v5:

I would to like change the controller folder path, to follow a new structure like:

```
-> app
  -> Modules
     -> Auth
        -> User
           -> Models
              - User.ts
           -> Controllers
              -> Http
                 - UserController.ts
```

I find into adonisjs code the follow section:
```javascript
getDestinationPath() {
    return this.getPathForNamespace('httpControllers') || 'app/Controllers/Http';
}
```

How can I define a new value to 'httpControllers'? In which file can I define it? 

Route example:
```javascript
Route.get('/api/v1/users', 'App/Modules/Auth/User/Controllers/Http/UserController.list')
```

**Comment by LuanMaik** [comment]
I solved making the follows changes:

Route:
```javascript
Route.get('/api/v1/usuarios', 'Modules/Auth/Usuario/Controllers/Http/UsuariosController.list')
```

providers/AppProvider.ts
```javascript
export default class AppProvider {
  public static needsApplication = true

  constructor(protected app: ApplicationContract) {
    app.namespacesMap.set('httpControllers', 'App')  # Here
  }
...
```

Is that the better aproach to resolve my case?

**Comment by thetutlage** [comment]
Most of the values are configurable within the `.adonisrc.json` file. Run the following command to see the available options.

```sh
node ace dump:rcfile
```

**Comment by thetutlage** [comment]
Also, I suggest using [Github discussions](https://github.com/adonisjs/core/discussions) as we keep issues specifically to issues that needs to be fixed and not for questions.
