### ISSUE TITLE
Unexpected non-whitespace character after JSON

### ISSUE THREAD

**Issue by bitkidd** [adonisjs/application#29]
### Package version

8.0.2

### Describe the bug

I am trying to create a stub that looks like this:

```hbs
{{#var passedValue = value}}
{{#var fileName = `${env}.credentials`}}
{{{
  exports({
    to: app.makePath('resources/credentials', fileName)
  })
}}}
{{ passedValue }}
```

And get an error: SyntaxError: Unexpected non-whitespace character after JSON at position ...

If I add some sort of a string (Ex: \s or \n) before `{{ passedValue }}`, it will work fine, but in my case this is not really an option.

Of course I can generate this file without stubs, but maybe that is something that can be fixed, as stubs are a recommended way of making this sort of operations.

**Comment by thetutlage** [comment]
Is that an issue specific to stubs or is that an issue coming directly from https://github.com/lukeed/tempura, the template engine we use under the hood?

**Comment by bitkidd** [comment]
I check tempura, it works fine.
Check it out here: https://replit.com/@bitkidd/LikelyShortArchives

Following the error stack the error lies in `#parseExports` which can error only in `parseStubExports `, which can fail in `JSON.parse`. I guess that's an edge case.s

The issue lies in [here](https://github.com/adonisjs/application/blob/6a9acbaa4e2b3b120b8be2894ed5696e65e29734/src/helpers.ts#L67), in the way you parse

**Comment by thetutlage** [comment]
Yeah, realized that later and fixed it
